### ISSUE TITLE
pod install fail on command cmd: 'cd ios && pod install && cd ..'

### ISSUE THREAD

**Issue by smunir** [ruddell/ignite-jhipster#86]
I am new to Jhipster, React and first timer with React Native. Trying to ignite application fails on mentioned command with below output error. 

```
➜  code git:(master) ✗ ignite new vimsmob --boilerplate ignite-jhipster                            
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app vimsmob
✔ Generating a React Native client for JHipster apps
✔ Enter the path to your JHipster project root directory: · /Users/shahzad/git/vims/code/vims
Looking for /Users/shahzad/git/vims/code/vims/.yo-rc.json
Found JHipster config file at /Users/shahzad/git/vims/code/vims/.yo-rc.json
✔ Do you want to enable end-to-end tests with Detox? (y/N) · false
Using npm as the package manager
✔ added React Native 0.60.5 in 74.93s
✔ using the JHipster boilerplate
✔ project generated
✔ set up react-native-navigation for iOS/Android
✔ dependencies installed
JHipster config saved to your app's .jhipster folder.
⠙ ▸ running pod installan error occured while installing ignite-jhipster boilerplate.
{ Error: Command failed: cd ios && pod install && cd ..

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd ios && pod install && cd ..',
  stderr: '' }
error installing boilerplate
➜  code git:(master) ✗ 

➜  code git:(master) ✗ node -v                        
v10.17.0
➜  code git:(master) ✗ npm -v                         
6.11.3
➜  code git:(master) ✗ react-native -v   
react-native-cli: 2.0.1
➜  vimsmob git:(master) ✗ pwd                                              
/Users/shahzad/git/vims/code/vimsmob

```
**Instructions To reproduce**

**JHipster app's `.yo-rc.json`**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxxx.edu.vims"
    },
    "jhipsterVersion": "6.4.1",
    "applicationType": "monolith",
    "baseName": "vims",
    "packageName": "com.xxxx.edu.vims",
    "packageFolder": "com/xxxx/edu/vims",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NDJlNTNiNjNkY2UzZWRkY2FkM2QwNjdjZjliZDNmMWQwMWYwYzg0M2U3ZjkzOWIxZmUwMjQ2YWM1ZTY2Nzg2YmMyZmMyOTI2ZGEzMTQ3ZDhlM2MwZDNlZWNlMTJlYWI2YTY4NzdjMmViYzNjOGRhMjVjMWUxODBmZjA5NjczZjE=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```
**Versions (please complete the following information):**
```
- Ignite JHipster Version: 3.3.1
- `ignite doctor` output:
➜  vimsmob git:(master) ✗ ignite doctor                                   
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                12 cores     Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz 
  directory          vimsmob      /Users/shahzad/git/vims/code/vimsmob     

JavaScript
  node               10.17.0      /usr/local/bin/node 
  npm                6.11.3       /usr/local/bin/npm  
  yarn               -            not installed       

Ignite
  ignite-cli         3.3.1                                                                                     /usr/local/bin/ignite                        
  ignite src         build                                                                                     /usr/local/lib/node_modules/ignite-cli/build 
  generators         {"entity":"ignite-jhipster","import-jdl":"ignite-jhipster","upgrade":"ignite-jhipster"}                                                

Android
  java               11.0.2       /Users/shahzad/.sdkman/candidates/java/current/bin/java 
  android home       -            undefined                                               

iOS
  xcode              -          
  cocoapods          1.8.4        /usr/local/bin/pod 
```

**Comment by ruddell** [comment]
Hi @smunir, thank you for the detailed report.  I was not able to reproduce on a first attempt.

 - Can you please provide the list of files/directories inside `/Users/shahzad/git/vims/code/vimsmob`?  

 - If you see an `ios` directory in there, can you try running the failing command:
    - `cd ios && pod install && cd ..`

I also added a try/catch to that command in https://github.com/ruddell/ignite-jhipster/commit/f563fa0f41b9d75fcf78e91e77871176b67eaa71 so if it fails, you can run it manually after generation.  I plan on releasing this in the near future once I find time to look into the CI failures.

**Comment by smunir** [comment]
Hi @ruddell, thanks for quick response. 

Here is tree structure of vimsmob with depth 3 (node_modules deleted)

ios folder is in /Users/shahzad/git/vims/code/vimsmob/vimsmob. Is there a reason for this nesting of folders. .../proj/proj/
```
➜  vimsmob git:(master) ✗ tree -L 3                 
.
├── package-lock.json
├── package.json
└── vimsmob
    ├── README.md
    ├── android
    │   ├── app
    │   ├── build.gradle
    │   ├── gradle
    │   ├── gradle.properties
    │   ├── gradlew
    │   ├── gradlew.bat
    │   └── settings.gradle
    ├── app
    │   ├── config
    │   ├── modules
    │   ├── navigation
    │   └── shared
    ├── app.json
    ├── babel.config.js
    ├── fastlane
    │   ├── Appfile
    │   ├── Fastfile
    │   └── Matchfile
    ├── ignite
    │   ├── ignite.json
    │   └── plugins
    ├── index.js
    ├── ios
    │   ├── Podfile
    │   ├── Pods
    │   ├── vimsmob
    │   ├── vimsmob-tvOS
    │   ├── vimsmob-tvOSTests
    │   ├── vimsmob.xcodeproj
    │   └── vimsmobTests
    ├── metro.config.js
    ├── package-lock.json
    ├── package.json
    ├── patches
    │   ├── @storybook+react-native+5.2.1.patch
    │   ├── README.md
    │   └── tcomb-form-native+0.6.20.patch
    ├── storybook
    │   ├── addons.js
    │   ├── index.js
    │   ├── rn-addons.js
    │   └── stories.js
    └── test
        ├── setup.js
        └── spec
```

cd ios && pod install && cd .. works in /Users/shahzad/git/vims/code/vimsmob/vimsmob

**Comment by smunir** [comment]
This might sound like a naive question, but how can I force ignite to use this particular commit while  generating project? I installed this commit as global package but generator still picking same 3.3.1 version

**Comment by ruddell** [comment]
I made a release with the try/catch around the failing command.  This should let your app finish generating.  Please let me know if the change works, thanks.  

Rerunning `ignite new vimsmob --boilerplate ignite-jhipster` will use the latest release.

The nested folder is a quirk of the `ignite-cli`, it uses `react-native` to init a project then copies the Ignite JHipster changes on top of the generated template.  After generation, the files are moved to the top-level folder.

**Comment by smunir** [comment]
Yes it did work and thanks for explaining nested folders

**Comment by ruddell** [comment]
Thanks again for reporting and testing. 👍
